# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=128)),
                ('date', models.CharField(default='', max_length=10)),
                ('author', models.CharField(default='', max_length=32)),
                ('up', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('down', models.IntegerField()),
                ('img_list', models.CharField(default='', max_length=10240)),
                ('kind', models.IntegerField()),
            ],
        ),
    ]
