# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ip',
            field=models.CharField(default='', max_length=32),
        ),
    ]
