# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_content_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.CharField(default='', max_length=32),
        ),
    ]
